### ISSUE TITLE
Properly type check APIs

### ISSUE THREAD

**Issue by CompeyDev** [itsfrank/frktest#2]
Currently, a lot of APIs for checks accept `any` (or some variation of it, like an array of `any`) which leads to a TypeError on properly typed projects.

For example, if I want to call `check.table.equal`, and I pass it a typed `Option` in strict mode, the following error will occur:
```
TypeError: Type 'Option' could not be converted into '{| [any]: any |}'
```

The solution to this is to properly type objects which can receive dynamic items as arguments using generics. In our above example, this means `check.table.equal` should accept become:
```luau
function <K, V>(this: { [K]: V }, that: { [K]: V }) end
```

Luau can now allow varying types for the indexes and values in the tables, inferring them dynamically. This also makes sure that both the tables at least have a similar shape (if possible) at typechecking time.

**Comment by itsfrank** [comment]
Interesting, would you be able to share a snippet of the test you wrote that caused the error? Where does this option type come from? 

I have to admit, I don't quite get how option would fail to match `{[any]:any}` but match a generic `{[K]:V}`, I would have to play around with it myself and see what works and doesn't, possible even discuss this with folks who are more familiar with the Luau type system.

I am open to having more precise types, but more importantly than having precise types is not excluding anything that would be a valid input to the check; which seems to be what is happening in your case, so I am interested in finding an appropriate solution.

I would need to test it out, but, one of my worries with `{[K]: V}` is that it would not allow tables with mixed key types, which I thought `{[any]:any}` did, but I will have to double check.

Maybe one way forward is to actually unspecify the signature to simply be:
```luau
function assert_impl.table_equal(a: unknown, b: unknown): Failure?
```
If you can share a snippet, I will try and find some time to look into this tomorrow

**Comment by CompeyDev** [comment]
If I have a table of some type `Option` with a metatable, it will no longer satisfy the condition of being a map of any kind, it is now a magical value.

But even with a generic table type, providing a sealed table wouldn't work, although it would provide typechecking between any two map tables. 

What I think would make most sense for comparison is to have a union of a singular generic `T` and a generic table shape. That way, people using unsealed "map" tables get basic typechecking, and any sealed table is also valid.

```luau
function <K, V, T>(this: { [K]: V } | T, that: { [K]: V } | T) end
````

**Comment by itsfrank** [comment]
> If I have a sealed table of some type `Option`

Can you provide an example so I can reproduce this type locally?

**Comment by CompeyDev** [comment]
I said a sealed table, but I meant to say a a sealed table *with a metatable*.

```luau
local function x(a: { [any]: any }) end
local function y<K, V, T>(a: { [K]: V } | T) end

local obj: Obj = {
    a = "hello",
    b = 123,
}
type Obj = {
    a: string,
    b: number?,
}

x(setmetatable(obj :: Obj, {})) -- TypeError
y(setmetatable(obj :: Obj, {})) -- This is fine
```

**Comment by itsfrank** [comment]
Ahh metatable, that makes sense, I did not test with those, thank you for the snippet!

**Comment by itsfrank** [comment]
So I played around a bit, and I think the right annotation for the table functions is unfortunately `table_eq(a: any, b: any)`

I was hopeful that this might work: `table_eq<K, V>(a: K & {}, b: V & {})`; it did work for regular tables, but not tables with metatables.

Thankfully, though the assertion does what I expect it to do for tables with metatables already, which is to check the non-meta members.

Thinking about your suggestion a bit, I'm fairly certain `{ [K]: V } | T` is effectively represents `any`, anything can "legally" bind to this type by just picking the right-hand of the `|`, and since we don't use the type in any return signature, there doesn't seem to be much value provided by the generics over `any`.

I think the best way to move forward for now is to make the table assertions just take `any` and maybe add a runtime check that the types passed in are indeed tables? What do you think?

**Comment by itsfrank** [comment]
I implemented this in https://github.com/itsfrank/frktest/tree/metatable-typechecking

**Comment by CompeyDev** [comment]
> there doesn't seem to be much value provided by the generics over any.

This allows some level of type-checking as I mentioned above, as opposed to any which entirely disables type-checking. With both the arguments being potentially a generic, it acts as any, and satisfies everything, but since they are the same generic, both the arguments must be of the same type itself. With any, you can compare entirely unrelated items and not know until your code runs, which is what such a type is supposed to prevent.

**Comment by itsfrank** [comment]
True, but I don't think we want that kind of typechecking, it's possible to have 2 tables of different types that are equal at runtime. E.g. this would pass the assertion but fails typechecking:

```luau
type A = { a: number, b: string? }
type C = { a: number }

local a: A = { a = 10 }
local c: C = { a = 10 }

function foo<T>(a: T, b: T) end

foo(a, c) -- TypeError: Table type 'C' not compatible with type 'A' because the former is missing field 'b' [1029]
```

Likewise, this would also pass the assertion, but fail type-checking:
```luau
local a = setmetatable({ a = 10 }, { foo = function() end })
local b = setmetatable({ a = 10 }, { bar = function() end })

function foo<T>(a: T, b: T) end

foo(a, b) -- TypeError: Type 'b' could not be converted into 'a'
          --  caused by:
          --    Table type '{ bar: () -> () }' not compatible with type '{ foo: () -> () }' because the former is missing field 'foo' [1000]
```

I'll move forward with any/any, and if we can find a type that typechecks that the inputs are table-ish without restricting the cases above, we can use that in the future. For now, runtime assertions will validate that.

**Comment by itsfrank** [comment]
Completed in 61280e92f624ba90016a52e7ccc81ccc5035e461
