### ISSUE TITLE
Publish frktest to pesde

### ISSUE THREAD

**Issue by CompeyDev** [itsfrank/frktest#3]
[Pesde](https://pesde.daimond113.com) is a package manager designed for Luau and Lune, as opposed to Wally which is purely a Roblox package manager, where frktest is currently published. 

It would make sense to publish frktest to Pesde as a Lune package. Temporarily, I've created a pesde-compatible fork of frktest at [CompeyDev/frktest/pesde](https://github.com/CompeyDev/frktest-pesde) that I am specifying as a git dependency in my project.

To get started with Pesde, consider viewing [the docs](https://docs.pesde.daimond113.com).

**Comment by itsfrank** [comment]
Done! Also created a sample project using pesde here: https://github.com/itsfrank/frktest-pesde-sample
